# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3)),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
