# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
