# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestLive.Exam')),
            ],
        ),
    ]
