# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0003_exam_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email_Address', models.CharField(max_length=100)),
                ('Contact_Detail', models.IntegerField(default='None')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='type',
            name='Type1',
        ),
        migrations.AlterField(
            model_name='exam',
            name='Date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
