# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0005_auto_20180630_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='E_Commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Net_Banking', models.CharField(max_length=30)),
                ('Credit', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unpaid', models.CharField(max_length=30)),
                ('Paid', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='choose_plan',
            name='select_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestLive.Plan'),
        ),
    ]
