# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0006_auto_20180630_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_commerce',
            old_name='Net_Banking',
            new_name='E_Commerce',
        ),
        migrations.RemoveField(
            model_name='e_commerce',
            name='Credit',
        ),
    ]
