# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0007_auto_20180630_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='Paid',
            new_name='Plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='Unpaid',
        ),
    ]
