# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0009_auto_20180630_0640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
