# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0010_auto_20180630_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analytic', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
