# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0014_auto_20180701_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GATE', models.ImageField(upload_to=b'')),
                ('SSC', models.ImageField(upload_to=b'')),
                ('RRB', models.ImageField(upload_to=b'')),
                ('RAILWAY', models.ImageField(upload_to=b'')),
                ('BANK', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
