# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0015_sets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sets',
            new_name='Set',
        ),
    ]
