# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0016_auto_20180701_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form', models.FileField(upload_to=b'')),
            ],
        ),
    ]
