# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0018_auto_20180702_0702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registratio',
            new_name='Registration',
        ),
        migrations.RenameModel(
            old_name='use',
            new_name='User',
        ),
    ]
