# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestLive', '0019_auto_20180702_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
    ]
