# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mathematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Physic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=50)),
                ('paper', models.CharField(max_length=50)),
            ],
        ),
    ]
